#!/usr/bin/env node
/* build.js — bundle Glide's ES modules into single classic scripts.
 *
 * WHY: ES-module `import` is blocked by browsers over the file:// protocol, so
 * double-clicking index.html/app.html leaves the app dead. This produces
 * dist/app.bundle.js and dist/landing.bundle.js as ordinary (non-module)
 * scripts that run over file://, http://, and GitHub Pages alike.
 *
 * The ES-module sources in src/ stay the source of truth (node --test uses
 * them, and http serving can use them). This bundler just re-packages them:
 *   • each module becomes __glideDef('name', (require) => { ... return exports })
 *   • static `import { a } from './x.js'` -> `const { a } = require('x')`
 *   • `export function/class/const NAME` -> declare NAME, add to exports
 *   • dynamic import() (MediaPipe CDN) is left untouched
 *
 * Run:  node build.js
 */
const fs = require('fs');
const path = require('path');

const SRC = path.join(__dirname, 'src');
const DIST = path.join(__dirname, 'dist');

// Bundles to emit: entry module + the modules it needs, in any order (the
// registry resolves lazily at runtime).
const BUNDLES = {
  'app.bundle.js': {
    entry: 'app',
    modules: ['filter', 'lexicon', 'cursor', 'gestures', 'predict', 'demopath', 'store', 'calibrate', 'scanning', 'tracker', 'app'],
  },
  'landing.bundle.js': {
    entry: 'scroll',
    modules: ['filter', 'hero3d', 'scroll'],
  },
};

// Transform one module's source into a registry factory body.
function transform(name) {
  const file = path.join(SRC, name + '.js');
  let code = fs.readFileSync(file, 'utf8');
  const lines = code.split('\n');
  const out = [];
  const exportNames = [];

  for (let line of lines) {
    // static import: `import { a, b } from './x.js';`  (NOT `await import(...)`)
    const imp = line.match(/^\s*import\s*\{([^}]+)\}\s*from\s*['"]\.\/([\w-]+)\.js['"];?\s*$/);
    if (imp) {
      const names = imp[1].trim();
      const dep = imp[2];
      out.push(`  const {${names}} = __glideReq('${dep}');`);
      continue;
    }
    // export declarations -> strip `export`, remember the name
    let m;
    if ((m = line.match(/^export\s+(async\s+)?function\s+([A-Za-z0-9_$]+)/))) {
      exportNames.push(m[2]); line = line.replace(/^export\s+/, '');
    } else if ((m = line.match(/^export\s+class\s+([A-Za-z0-9_$]+)/))) {
      exportNames.push(m[1]); line = line.replace(/^export\s+/, '');
    } else if ((m = line.match(/^export\s+(const|let|var)\s+([A-Za-z0-9_$]+)/))) {
      exportNames.push(m[2]); line = line.replace(/^export\s+/, '');
    } else if (/^export\s*\{/.test(line)) {
      // `export { a, b };` — collect names, drop the line
      const inner = line.match(/\{([^}]+)\}/);
      if (inner) inner[1].split(',').forEach((n) => exportNames.push(n.trim().split(/\s+as\s+/).pop()));
      continue;
    }
    out.push('  ' + line);
  }

  const ret = `\n  return { ${[...new Set(exportNames)].join(', ')} };`;
  return `__glideDef('${name}', function(__glideReq){\n${out.join('\n')}${ret}\n});`;
}

const RUNTIME = `/* Glide bundle — generated by build.js. Do not edit by hand.
   A tiny module registry so the ES-module sources run as one classic script
   (works over file://). Edit src/*.js and re-run \`node build.js\`. */
(function(){
  var __mods = {}, __cache = {};
  function __glideDef(name, factory){ __mods[name] = factory; }
  function __glideReq(name){
    if (__cache[name]) return __cache[name];
    var f = __mods[name];
    if (!f) throw new Error('Glide bundle: missing module ' + name);
    var exports = f(__glideReq);
    __cache[name] = exports;
    return exports;
  }
`;

function buildOne(outName, spec) {
  const parts = [RUNTIME];
  for (const m of spec.modules) parts.push(transform(m));
  parts.push(`  __glideReq('${spec.entry}');`); // run the entry
  parts.push('})();');
  const bundle = parts.join('\n\n');
  fs.mkdirSync(DIST, { recursive: true });
  fs.writeFileSync(path.join(DIST, outName), bundle);
  return bundle.length;
}

let total = 0;
for (const [outName, spec] of Object.entries(BUNDLES)) {
  const size = buildOne(outName, spec);
  total += size;
  console.log(`  dist/${outName}  (${(size / 1024).toFixed(1)} KB)`);
}
console.log(`  Done — ${(total / 1024).toFixed(1)} KB total.`);
